#!/usr/bin/env python

# -------- USING THE SHEBANG ABOVE... 
#              We can redirect the compiler to the Python executable that runs scripts.
#!/usr/bin/env python
# -------- Below code allows python script to be executable...
# chmod +x myecho.py
# -------- Below code removes extension to make it look like a cmd-line tool.
# Then doing "mv ip_search.py ip_search"
# -------- First, you need to create the ~/bin directory:
# mkdir -p ~/bin
# -------- Next, copy your script to ~/bin:
# cp myecho ~/bin
# -------- Finally, add ~/bin to your PATH:
# export PATH=$PATH":$HOME/bin"
# -------- [ TAKEN FROM  https://dbader.org/blog/how-to-make-command-line-commands-with-python ]

import sys
import os
print(os.sys.path)

for arg in sys.argv:
  print(arg)

# request = scapy.ARP()

# request.pdst = 'x'
# broadcast = scapy.Ether()

# broadcast.dst = 'ff:ff:ff:ff:ff:ff'

# request_broadcast = broadcast / request
# clients = scapy.srp(request_broadcast, timeout=1)[0]
# for element in clients:
#   print(element[1].psrc + "     " + element[1].hwsrc)
